apiVersion: 1

datasources:
  # ORG 1 - Main Org
  - name: Loki
    uid: DS_LOKI
    orgId: 1
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      httpHeaderName1: ""
